remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Cuttlephone
description: Phone case generator with gaming in mind
logo: https://user-images.githubusercontent.com/1850819/146625509-2912b6e2-4588-4564-96ca-3bf1879dbf04.png
github: [metadata]
